"""add shop tables

Revision ID: fe69da2a8b79
Revises: 8d5f5bbc1169
Create Date: 2026-10-01 11:47:56.353250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe69da2a8b79'
down_revision: Union[str, Sequence[str], None] = '8d5f5bbc1169'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shops',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('owner_user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=60), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('min_notice_minutes', sa.Integer(), nullable=False),
    sa.Column('max_days_ahead', sa.Integer(), nullable=False),
    sa.Column('cancel_window_minutes', sa.Integer(), nullable=False),
    sa.Column('slot_step_minutes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.CheckConstraint('cancel_window_minutes >= 0', name=op.f('ck_shops_cancel_window_not_negative')),
    sa.CheckConstraint('max_days_ahead BETWEEN 1 AND 365', name=op.f('ck_shops_max_days_ahead_range')),
    sa.CheckConstraint('min_notice_minutes >= 0', name=op.f('ck_shops_min_notice_not_negative')),
    sa.CheckConstraint('slot_step_minutes IN (5, 10, 15, 20, 30, 60)', name=op.f('ck_shops_slot_step_allowed')),
    sa.ForeignKeyConstraint(['owner_user_id'], ['user.id'], name=op.f('fk_shops_owner_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shops'))
    )
    op.create_index(op.f('ix_shops_owner_user_id'), 'shops', ['owner_user_id'], unique=True)
    op.create_index(op.f('ix_shops_slug'), 'shops', ['slug'], unique=True)
    op.create_table('shop_closures',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('closed_on', sa.Date(), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], name=op.f('fk_shop_closures_shop_id_shops'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shop_closures')),
    sa.UniqueConstraint('shop_id', 'closed_on', name=op.f('uq_shop_closures_shop_id'))
    )
    op.create_index(op.f('ix_shop_closures_shop_id'), 'shop_closures', ['shop_id'], unique=False)
    op.create_table('shop_hours',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('weekday', sa.SmallInteger(), nullable=False),
    sa.Column('open_time', sa.Time(), nullable=False),
    sa.Column('close_time', sa.Time(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('close_time > open_time', name=op.f('ck_shop_hours_open_before_close')),
    sa.CheckConstraint('weekday BETWEEN 0 AND 6', name=op.f('ck_shop_hours_weekday_range')),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], name=op.f('fk_shop_hours_shop_id_shops'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shop_hours')),
    sa.UniqueConstraint('shop_id', 'weekday', name=op.f('uq_shop_hours_shop_id'))
    )
    op.create_index(op.f('ix_shop_hours_shop_id'), 'shop_hours', ['shop_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shop_hours_shop_id'), table_name='shop_hours')
    op.drop_table('shop_hours')
    op.drop_index(op.f('ix_shop_closures_shop_id'), table_name='shop_closures')
    op.drop_table('shop_closures')
    op.drop_index(op.f('ix_shops_slug'), table_name='shops')
    op.drop_index(op.f('ix_shops_owner_user_id'), table_name='shops')
    op.drop_table('shops')
    # ### end Alembic commands ###
